name: ledger_view
description: A modern Flutter app to view customer ledger data from Google Sheets

publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  csv: ^5.1.1
  shared_preferences: ^2.3.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.13.0
  excel: ^2.0.0
  provider: ^6.1.1
  share_plus: ^7.2.2
  path_provider: ^2.1.1
  image: ^4.0.0
  url_launcher: ^6.2.2
  whatsapp_share2: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
